language: node_js
sudo: false
node_js:
- '8'
cache:
  directories:
  - node_modules
install: npm install
script:
  - npm run lint
  - npm run build
deploy:
  - provider: script
    script: ./scripts/internal_travis_trigger.sh
    skip_cleanup: true
    on:
      branch: master
