version: '3'
services:
  sdk-example:
    image: containers.schibsted.io/spt-identity/sdk-example
    environment:
      - CLIENT_ID=UNDEFINED
      - CLIENT_SECRET=UNDEFINED
      - NODE_ENV=development
      - PORT=9000
    ports:
      - "9000:9000"
